// <auto-generated />
namespace WinFormsCrud.Migrations
{/*
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addManagerToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addManagerToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202408102047388_addManagerToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }*/
}
