// <auto-generated />
namespace WinFormsCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InsertSampleCases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertSampleCases));
        
        string IMigrationMetadata.Id
        {
            get { return "202408101726132_InsertSampleCases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
